services:
  nginx:
    image: nginx:alpine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${NGINX_PORT:-9080}:9080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - wp-core:/var/www/html
      - ../wp-content:/var/www/html/wp-content
      - ../vendor:/var/www/html/vendor
    depends_on:
      wordpress:
        condition: service_started

  wordpress:
    build: ./wordpress
    ports:
      - "3000:3000"
    volumes:
      - wp-core:/var/www/html
      - ../wp-content:/var/www/html/wp-content
      - ../config/wp-config.php:/var/www/html/wp-config.php
      - ../composer.json:/var/www/html/composer.json
      - ../vendor:/var/www/html/vendor
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WP_ENV: ${WP_ENV}

  db:
    image: mariadb:10.6
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

volumes:
  wp-core:
  db_data: